function FindProxyForURL(url, host) {
  var victims = new Array
  ( "acm.org"
  , "archbang.org"
  , "domains.google"
  , "lists.ocaml.org"
  , "nvidia.com"
  , "noredink.com"
  // , "rebar3.org"
  , "schoolofhaskell.com"
  , "resilio.com"
  , "yougowords.com"
  , "cedeela.fr"
  , "issuu.com"
  , "gist.github.com"
  , "lumioapp.com"
  , "tumblr.com"
  , "disqus.com"
  , "apptorium.com"
  , "shkspr.mobi"
  , "dmtry.com"
  // , "yandex.com"
  , "shutterstock.com"
  // , "haskell.org"
  , "stackage.org"
  , "wikileaks.org"
  , "qiwen.lu"
  , "telegram.org"
  , "chinadigitaltimes.net"
  , "epochtimes.com"
  , "bannedbook.net"
  , "draw.io"
  // , "elm-lang.org"
  , "instagram.com"
  , "wolfram.com"
  , "wolframcloud.com"
  , "battlestarwiki.org"
  , "spotify.com"
  , "archive.org"
  , "bloomberg.com"
  , "nautil.us"
  , "pastebin.com"
  , "medium.com"
  , "arstechnica.com"
  , "deepmind.com"
  , "knowyourmobile.com"
  , "yibada.com"
  , "googleblog.com"
  , "ssa.gov"
  , "udacity.com"
  , "schemasync.org"
  , "tensorflow.org"
  // , "coursera.org"
  , "nytimes.org"
  , "nytimes.com"
  , "cloudfront.net"
  , "pastebin.com"
  , "bestvpnservice.com"
  , "purevpn.com"
  , "lemire.me"
  // , "cloudfront.net"
  , "tamewildsystems.com"
  , "darcs.net"
  , "r2d3.us"
  , "wireshark.org"
  , "haxx.se"
  , "youtu.be"
  , "getlantern.org"
  , "dreamhost.com"
  , "bbc.com"
  , "gameloft.com"
  // , "digitalocean.com"
  , "dropboxusercontent.com"
  , "bestvpnchina.net"
  , "soundcloud.com"
  , "vimeo.com"
  , "twimg.com"
  , "fastly.net"
  , "softether.org"
  , "softether-download.com"
  , "erlang.org"
  , "appspot.com"
  , "haskellforall.com"
  , "wp.com"
  , "goldenfrog.com"
  , "strongvpn.com"
  , "android.com"
  , "w3schools.com"
  , "tldp.org"
  , "jeasyui.com"
  , "nptel.ac.in"
  , "tamewildsystems.com"
  , "gravatar.com"
  , "aspnetcdn.com"
  , "bit.ly"
  // , "awsstatic.com"
  , "sstatic.net"
  , "berkeley.edu"
  , "blogspot.com"
  , "blogspot.fr"
  , "blogspot.co"
  , "blogspot.dk"
  , "blogspot.be"
  , "blogger.com"
  , "blogblog.com"
  , "blogblog.ca"
  , "bulkrenameutility.co.uk"
  , "careercup.com"
  , "dartdocs.org"
  , "devio.us"
  // , "duckduckgo.com"
  , "evernote.com"
  , "facebook.com"
  , "forkio.com"
  , "freeweibo.com"
  , "galois.com"
  // , "github.com"
  , "golang.org"
  , "google.com"
  , "googleapis.com"
  , "googlecode.com"
  , "googleusercontent.com"
  , "googlevideo.com"
  , "google-analytics.com"
  , "ggpht.com"
  , "greatfire.org"
  , "gstatic.com"
  , "glump.net"
  , "icu-project.org"
  // , "images-amazon.com"
  , "imgur.com"
  // , "amazon.com"
  , "inkscape.org"
  , "kfish.org"
  , "marc.info"
  , "media-imdb.com"
  , "mit.edu"
  , "moertel.com"
  , "nabble.com"
  , "nocookie.net"
  , "openvpn.net"
  , "oppia.org"
  , "pao-pao.net"
  , "pinger.com"
  , "pixnet.net"
  , "polymer-project.org"
  , "postimg.org"
  , "quantserve.com"
  , "reddit.com"
  , "redditmedia.com"
  , "redditstatic.com"
  // , "amazonaws.com"
  , "seleniumhq.org"
  , "sf.net"
  , "shadowsocks.org"
  , "sigfpe.com"
  , "skype.com"
  , "slideshare.net"
  // , "solidot.org"
  , "sourceforge.net"
  // , "subscene.com"
  , "torproject.org"
  , "twitter.com"
  , "uu.nl"
  , "vpngate.net"
  , "wikia.com"
  , "wikimedia.org"
  , "wikipedia.org"
  , "wordpress.com"
  , "wp.com"
  , "wsj.com"
  , "ycombinator.com"
  , "geocities.com"
  , "youtube.com"
  , "ytimg.com"
  );

  for(var i=0; i<victims.length; i++) {
    var victim = "*" + victims[i] + "*";
    if (shExpMatch(url, "*"+victim+"*")) {
      return "SOCKS5 localhost:9050";
    }
  }
  return "DIRECT";
}
