function FindProxyForURL(url, host) {
  var victims = new Array
  ( "acm.org"
  , "archbang.org"
  , "gameloft.com"
  , "bestvpnchina.net"
  , "vimeo.com"
  , "fastly.net"
  , "softether.org"
  , "softether-download.com"
  , "erlang.org"
  , "images-amazon.com"
  , "appspot.com"
  , "haskellforall.com"
  , "wp.com"
  , "goldenfrog.com"
  , "strongvpn.com"
  , "android.com"
  , "w3schools.com"
  , "tldp.org"
  , "jeasyui.com"
  , "nptel.ac.in"
  , "tamewildsystems.com"
  , "gravatar.com"
  , "aspnetcdn.com"
  , "bit.ly"
  , "awsstatic.com"
  , "sstatic.net"
  , "berkeley.edu"
  , "blogspot.com"
  , "blogspot.co"
  , "blogger.com"
  , "blogblog.com"
  , "bulkrenameutility.co.uk"
  , "careercup.com"
  , "dartdocs.org"
  , "devio.us"
  , "duckduckgo.com"
  , "evernote.com"
  , "facebook.com"
  , "forkio.com"
  , "freeweibo.com"
  , "galois.com"
  , "github.com"
  , "golang.org"
  , "google.com"
  , "googleapis.com"
  , "googlecode.com"
  , "googleusercontent.com"
  , "googlevideo.com"
  , "google-analytics.com"
  , "ggpht.com"
  , "greatfire.org"
  , "gstatic.com"
  , "glump.net"
  , "icu-project.org"
  , "images-amazon.com"
  , "imgur.com"
  , "inkscape.org"
  , "kfish.org"
  , "marc.info"
  , "media-imdb.com"
  , "mit.edu"
  , "moertel.com"
  , "nabble.com"
  , "nocookie.net"
  , "openvpn.net"
  , "oppia.org"
  , "pao-pao.net"
  , "pinger.com"
  , "pixnet.net"
  , "polymer-project.org"
  , "postimg.org"
  , "quantserve.com"
  , "reddit.com"
  , "redditmedia.com"
  , "redditstatic.com"
  , "s3.amazonaws.com"
  , "seleniumhq.org"
  , "sf.net"
  , "shadowsocks.org"
  , "sigfpe.com"
  , "skype.com"
  , "slideshare.net"
  // , "solidot.org"
  , "sourceforge.net"
  // , "subscene.com"
  , "torproject.org"
  , "twitter.com"
  , "uu.nl"
  , "vpngate.net"
  , "wikia.com"
  , "wikimedia.org"
  , "wordpress.com"
  , "wsj.com"
  , "ycombinator.com"
  , "youtube.com"
  , "ytimg.com"
  , "cdn.com"
  );

  for(var i=0; i<victims.length; i++) {
    var victim = "*" + victims[i] + "*";
    if (shExpMatch(url, "*"+victim+"*")) {
      return "SOCKS5 localhost:9050";
    }
  }
  return "DIRECT";
}
